# Generated by Django 4.2.3 on 2023-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_department_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="sex",
            field=models.IntegerField(default=0),
        ),
    ]
