# Generated by Django 4.2.3 on 2023-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_userinfo_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="sex",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
